const CONSTANTS = {
    // header content
    headerTitleLabel: 'CoLiv App',
    headerTenantLinkLabels: ['Availability', 'Booking', 'Account'],
    headerResidenceAdminLinkLabels: ['Employees', 'Tenants', 'Assets'],

    // routes
    availabilityRoute: '/availability',
    bookingRoute: '/booking',
    accountRoute: '/account',
    loginRoute: '/auth/login',
    forgotPasswordRoute: '/auth/forgot-password',
    resetPasswordRoute: '/auth/reset-password',
    homeRoute: '/',
    residenceAdminRoute: '/residence-admin',
    tenantsRoute: '/residence-admin/tenants',
    laundryAssetsRoute: '/residence-admin/laundry-assets',

    logoutLabel: 'Logout',

    // availability page content
    rulesOnUseLabel: 'Rules on Use',
    rulesOnUse: [
        '1. Tenants are kindly asked to be respectful when using their booked time slots.\
            \nThis includes picking up their laundry promptly after the use.',
        '2. Tenants are kindly asked to use laundry machines with care. \
            \nThis includes saftely operating the machines, from the start until the end of their operation. \
            \nThe machines are not to be openned during their operation time.',
        '3. Tenants are to take utmost care not to put sharp objects in the machines, or objects of any kind which \
        could compromise optimal functioning of the machines. \
            \nPlease thoroughly check your clothes and empty your pockets before using the machines.',
        '4. Tenants are to take utmost care not to put overly stained clothes in the machines if they estimate \
            their washing would compromise optimal washing job for the tenants which will use the machines after them.',
        '5. Tenants are not to put their own detergent in the machines which already come equiped with the detergent.\
            \nThese machines are marked by special labels.'
    ],
    useMachinesLabel: 'Use Machines',
    availabilityLabel: 'Availability',
    assetLabel: 'Asset',
    noteLabel: 'Note',
    actionLabel: 'Action',
    useLabel: 'Use',
    usingLabel: 'Using',
    bookLabel: 'Book',
    availableImmediatelyLabel: 'Available Immediately',
    assetFinishesAtLabel: 'Asset finishes running at',
    youBookedThisAssetOnLabel: 'You have a booking on ',
    youBookedThisAssetUntilLabel: 'You have a booking until ',
    notInUseLabel: 'Not in use',
    availableOnLabel: 'Available on',
    currentlyNotOperationalLabel: 'Asset is not operational',
    paymentConfirmationTitleLabel: 'Payment Confirmation',
    confirmPaymentLabel: 'Confirm Payment',
    useCardLabel: 'Use Card',
    usePointsLabel: 'Use Points',
    confirmPaymentErrorMsg: 'Something went wrong.\nPlease try again.',

    // booking page content
    myBookingsLabel: 'My Bookings',
    myActiveTimeslots: 'My Active Timeslots',
    bookNowLabel: 'Book Now',
    timeslotLabel: 'Timeslot',
    confirmBookingLabel: 'Confirm Booking',
    bookingConfirmationTitleLabel: 'Booking Confirmation',
    confirmBookingErrorMsg: 'Something went wrong.\nPlease try again.',
    fromLabel: 'From',
    untilLabel: 'Until',
    selectAssetLabel: 'Select an asset',
    purchaseOptionExpired: 'This asset can no longer be purchased',
    laundryAssetPurchased: 'You have purchased this asset',
    noExpiredBookings: 'You have no bookings which have expired',
    noCurrentlyRunnningBookings: 'You have no currently running bookings',
    noBookingsReadyForUse: 'You have no bookings which are ready to be used',

    // account page content
    infoLabel: 'Info',
    paymentLabel: 'Payment', 
    activityHistoryLabel: 'Activity History',
    loyaltyProgramLabel: 'Loyalty Program',
    yourLoyaltyPointsLabel: 'Your Loyalty Points',
    buyLabel: 'Buy',
    timeOfActivityLabel: 'Time of Activity',
    activityLabel: 'Activity',
    chosenTimeslotLabel: 'Chosen Timeslot',
    descriptionLabel: 'Description',
    freeOfChargeLabel: 'Free',
    paidAmountLabel: 'Paid Amount',
    bookingLabel: 'Booking',
    usernamePlaceholder: 'username',
    emailPlaceholder: 'email',
    mobileNumberPlaceholder: 'mobile number',
    updateLabel: 'Update',
    updateInfoErrorMsg: 'Something went wrong.\nPlease try again.',
    cardNumberPlaceholder: 'card number',
    cardHolderPlaceholder: 'card holder name',
    cardExpiryDatePlaceholder: 'MM/YY',
    cvvPlaceholder: 'CVV',
    registerCardLabel: 'Register Card',
    registerPaymentErrorMsg: 'Something went wrong.\nPlease try again.',
    accommodationInformationLabel: 'Accommodation Information',
    residenceNameLabel: 'Residence Name',
    residenceAddressLabel: 'Residence Address',
    unitNumberLabel: 'Unit Number',
    curretPaymentMethodLabel: 'Current Payment Card',
    inactivePaymentMethodsLabel: 'Previous Payment Cards',
    accountInfoFormIsInvalid: 'Please provide valid email and mobile number',
    registerPaymentFormIsInvalid: 'Please provide valid card information',
    noRegisteredActivities: 'You have no registered activities yet',
    noRegisteredPaymentCards: 'You have no registered payment cards yet',
    noLoyaltyOffers: 'There are no offers at the moment',

    // auth pages content
    usernameValidationError: 'Username must be at least 6 characters long',
    passwordValidationError: 'Password must be at least 6 characters long',
    confirmedPasswordValidationError: 'Entered passwords do not match',
    fogotMyPassword: 'Forgot my password',
    loginLabel: 'Login',
    requestPasswordLabel: 'Request Password',
    forgotPasswordLabel: 'Forgot Password',
    resetPasswordLabel: 'Reset Password',
    loginErrorMessage: 'Unsuccessful Login',
    resetPasswordBadRequestError: 'Invalid attempt to reset password',
    toLoginPageLabel: 'To Login Page',
    

    // admin page content
    registerResidenceAdminLabel: 'Register Residence Admin',
    updateResidenceAdminLabel: 'Update Residence Admin',
    registerTenantLabel: 'Register Tenant',
    updateTenantLabel: 'Update Tenant',
    registerLaundryAssetLabel: 'Register Laundry Asset',
    updateLaundryAssetLabel: 'Update Laundry Asset',
    nameValidationError: 'Name must be at least 2 characters long',
    emailValidationError: 'Please insert the correct email',
    priceValidationError: 'Price must be larger than 0',
    runningTimeValidationError: 'Running time must be at least 1 minute',
    mobileNumberValidationError: 'Please insert the correct mobile number',
    registerLabel: 'Register',
    dateMustNotBeInPast: 'Date must not be in the past',
    tenancyMustBeAtLeastOneMonth: 'The tenancy must be at least 30 days',
    nameLabel: 'Name',
    pointsLabel: 'Points',
    priceLabel: 'Price',
    expiryDateLabel: 'Expiry Date',
    tenancyPeriodLabel: 'Tenancy Period',
    contactLabel: 'Contact',
    assetTypeLabel: 'Asset Type',
    noRegisteredTenantsLabel: 'No Tenants have been Registered yet',
    noRegisteredResidenceAdminsLabel: 'No Employees have been registered yet',
    noRegisteredLaundryAssetsLabel: 'No Laundry assets have been registered yet',
    removeLabel: 'Remove',
    cancelTenancyLabel: 'Cancel Tenancy',
    tenancyCancellationLabel: 'Tenancy Cancellation',
    tenancyCancellationContent: "You are about to cancel the user's tenancy.\n\nAre you sure you wish to proceed?",
    tenancyCancellationErrorMsg: 'The cancellation was unsuccessful',
    registeredTenantsLabel: 'Registered Tenants',
    registeredResidenceAdminsLabel: 'Registered Employees',
    registeredLaundryAssetsLabel: 'Registered Laundry Assets',
    registerResidenceAdminSectionIndex: 0,
    updateResidenceAdminSectionIndex: 1,
    registerTenantSectionIndex: 0,
    updateTenantSectionIndex: 1,
    registerLaundryAssetIndex: 0,
    updateLaundryAssetIndex: 1,
    washerLabel: 'Washer',
    drierLabel: 'Drier',
    selectAssetTypeLabel: 'Select asset type:',
    isOperationalLabel: 'Is Operational',
    defaultDropdownCurrency: 'MYR',
    supportedCurrencies: ['MYR', 'USD', 'SGD'],
    insertTimeInMinutesLabel: 'In minutes',
    
    // footer content
    allRightsReservedLabel: '© 2023 All rights reserved to Millennium Living',

    // store content
    usernameLabelLocalStorage: 'username',
    userRoleLabelLocalStorage: 'userRole',
    userLoyaltyPointsStorage: 'loyaltyPoints',
    userJwtLabelLocalStorage: 'userJwt',

    // general
    fulfilledLabel: 'fulfilled',
    unknownType: 'Uknown Type',
    pleaseInsertValidData: 'Please insert the valid data',
    defaultDropdownValue: -1,
    hoursInDay: 24,
    firstHourOfDay: 0,
    beApiRolePrefix: 'ROLE_',
    unanticipatedEvent: 'Unanticipated Event Occured',
    theDataCannotBeFetchedMomentarily: 'Our systems are currently unavailable. Please try again later.',

    // country dial codes
    DIAL_CODE_MY: '+60',
    DIAL_CODE_SG: '+65',
    DIAL_CODE_TH: '+66',
    DIAL_CODE_ID: '+62',
    DIAL_CODE_PH: '+63',
    DIAL_CODE_VN: '+84',
    DIAL_CODE_LA: '+856',
    DIAL_CODE_KH: '+855',
    DIAL_CODE_MM: '+95',
    DIAL_CODE_AU: '+61',
    unknownDialCodeError: 'An uknown dial code has been entered',
}

export default CONSTANTS;
