const CONSTANTS = {
    // header content
    headerTitleLabel: 'CoLiv App',
    headerLinkLabels: ['Availability', 'Booking', 'Account'],

    // routes
    availabilityRoute: '/availability',
    bookingRoute: '/booking',
    accountRoute: '/account',
    loginRoute: '/login',
    homeRoute: '/',
    residenceAdminRoute: '/residence-admin',

    logoutLabel: 'Logout',

    // availability page content
    availabilityLabel: 'Availability',
    assetLabel: 'Asset',
    noteLabel: 'Note',
    actionLabel: 'Action',
    useLabel: 'Use',
    usingLabel: 'Using',
    bookLabel: 'Book',
    availableImmediatelyLabel: 'Available Immediately',
    machineFinishesAtLabel: 'Machine finishes running at',
    youBookedThisMachineOnLabel: 'You have a booking on ',
    youBookedThisMachineUntilLabel: 'You have a booking until ',
    availableOnLabel: 'Available on',
    paymentConfirmationTitleLabel: 'Payment Confirmation',
    confirmPaymentLabel: 'Confirm Payment',
    confirmPaymentErrorMsg: 'Something went wrong.\nPlease try again.',

    // booking page content
    myBookingsLabel: 'My Bookings',
    myActiveTimeslots: 'My Active Timeslots',
    bookNowLabel: 'Book Now',
    timeslotLabel: 'Timeslot',
    confirmBookingLabel: 'Confirm Booking',
    bookingConfirmationTitleLabel: 'Booking Confirmation',
    confirmBookingErrorMsg: 'Something went wrong.\nPlease try again.',
    fromLabel: 'From',
    untilLabel: 'Until',
    selectAssetLabel: 'Select an asset',
    purchaseOptionExpired: 'This asset can no longer be purchased',
    laundryAssetPurchased: 'You have purchased this asset',
    noExpiredBookings: 'You have no bookings which have expired',
    noCurrentlyRunnningBookings: 'You have no currently running bookings',
    noBookingsReadyForUse: 'You have no bookings which are ready to be used',

    // account page content
    infoLabel: 'Info',
    paymentLabel: 'Payment', 
    activityHistoryLabel: 'Activity History',
    timeOfActivityLabel: 'Time of Activity',
    activityLabel: 'Activity',
    chosenTimeslotLabel: 'Chosen Timeslot',
    paidAmountLabel: 'Paid Amount',
    bookingLabel: 'Booking',
    usernamePlaceholder: 'username',
    emailPlaceholder: 'email',
    mobileNumberPlaceholder: 'mobile number',
    updateLabel: 'Update',
    updateInfoErrorMsg: 'Something went wrong.\nPlease try again.',
    cardNumberPlaceholder: 'card number',
    cardHolderPlaceholder: 'card holder name',
    cardExpiryDatePlaceholder: 'MM/YY',
    cvvPlaceholder: 'CVV',
    registerCardLabel: 'Register Card',
    registerPaymentErrorMsg: 'Something went wrong.\nPlease try again.',
    accommodationInformationLabel: 'Accommodation Information',
    residenceNameLabel: 'Residence Name',
    residenceAddressLabel: 'Residence Address',
    unitNumberLabel: 'Unit Number',
    curretPaymentMethodLabel: 'Current Payment Card',
    inactivePaymentMethodsLabel: 'Previous Payment Cards',
    formIsInvaildMsg: 'Please insert the information correctly',
    noRegisteredActivities: 'You have no registered activities yet',
    noRegisteredPaymentCards: 'You have no registered payment cards yet',

    // login page content
    usernameValidationError: 'Username must be at least 6 characters long',
    passwordValidationError: 'Password must be at least 6 characters long',
    fogotMyPassword: 'Forgot my password',
    loginLabel: 'Login',
    loginErrorMessage: 'Unsuccessful Login',

    // admin page content
    registerResidenceAdminLabel: 'Register Residence Admin',
    updateResidenceAdminLabel: 'Update Residence Admin',
    registerTenantLabel: 'Register Tenant',
    updateTenantLabel: 'Update Tenant',
    registerLaundryAssetLabel: 'Register Laundry Asset',
    updateLaundryAssetLabel: 'Update Laundry Asset',
    nameValidationError: 'Name must be at least 2 characters long',
    emailValidationError: 'Please insert the correct email',
    priceValidationError: 'Price must be larger than 0',
    runningTimeValidationError: 'Running time must be at least 1 minute',
    mobileNumberValidationError: 'Please insert the correct mobile number',
    registerLabel: 'Register',
    dateMustNotBeInPast: 'Date must not be in the past',
    tenancyMustBeAtLeastOneMonth: 'The tenancy must be at least 30 days',
    nameLabel: 'Name',
    tenancyPeriodLabel: 'Tenancy Period',
    contactLabel: 'Contact',
    assetTypeLabel: 'Asset Type',
    noRegisteredTenantsLabel: 'No Tenants have been Registered yet',
    noRegisteredResidenceAdminsLabel: 'No Employees have been registered yet',
    noRegisteredLaundryAssetsLabel: 'No Laundry assets have been registered yet',
    removeLabel: 'Remove',
    cancelTenancyLabel: 'Cancel Tenancy',
    tenancyCancellationLabel: 'Tenancy Cancellation',
    tenancyCancellationContent: "You are about to cancel the user's tenancy.\n\nAre you sure you wish to proceed?",
    tenancyCancellationErrorMsg: 'The cancellation was unsuccessful',
    registeredTenantsLabel: 'Registered Tenants',
    registeredResidenceAdminsLabel: 'Registered Employees',
    registeredLaundryAssetsLabel: 'Registered Laundry Assets',
    registerResidenceAdminSectionIndex: 0,
    updateResidenceAdminSectionIndex: 1,
    registerTenantSectionIndex: 2,
    updateTenantSectionIndex: 3,
    registerLaundryAssetIndex: 4,
    updateLaundryAssetIndex: 5,
    washerLabel: 'Washer',
    drierLabel: 'Drier',
    selectAssetTypeLabel: 'Select asset type:',
    isOperationalLabel: 'Is Operational?',
    defaultDropdownCurrency: 'MYR',
    supportedCurrencies: ['MYR', 'USD', 'SGD'],
    insertTimeInMinutesLabel: 'In minutes',
    
    // footer content
    allRightsReservedLabel: '© 2023 All rights reserved to Millennium Living',

    // store content
    usernameLabelLocalStorage: 'username',
    userRoleLabelLocalStorage: 'userRole',
    userJwtLabelLocalStorage: 'userJwt',

    // general
    fulfilledLabel: 'fulfilled',
    unknownType: 'Uknown Type',
    pleaseInsertValidData: 'Please insert the valid data',
    defaultDropdownValue: -1,
    hoursInDay: 24,
    firstHourOfDay: 0,
    beApiRolePrefix: 'ROLE_',
    unanticipatedEvent: 'Unanticipated Event Occured',
    theDataCannotBeFetchedMomentarily: 'Our systems are currently unavailable. Please try again later.'

}

export default CONSTANTS;
